
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
const inter = Montserrat({ subsets: ["latin"] });

import { NextUIProvider } from '@nextui-org/react'
import { Providers } from "./providers/providers";
import { AppProvider } from "./context/AppProvider/Provider";
import { Inter as FontSans } from "next/font/google"
import { UserProvider } from '@auth0/nextjs-auth0/client';
import toast, { Toaster } from 'react-hot-toast';
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "./firebaseConfig";
import Left from "./components/Left";
import Rigth from "./components/Rigth";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (

    <html lang="en">

      <UserProvider>
        <AppProvider  >

          <body className={inter.className}>
            <div className=" relative w-full">
              <Toaster
                position="top-center"
                reverseOrder={false}
              />
              <Left />

              <Rigth>
                {children}
              </Rigth>



            </div>

          </body>

        </AppProvider>
      </UserProvider>



    </html>




  );
}
